{% set name = "ibis-vega-transform" %}
{% set version = "5.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Quansight/{{ name }}/archive/{{ version }}.tar.gz
  sha256: a36e866358e45a55d1cf82807004d0ef0a5022c5e460eed537d99dffabdb53d8

build:
  noarch: python
  number: 0

requirements:
  host:
    - python >=3.7
    - nodejs >=12
    - pip
  run:
    - python >=3.7
    - jaeger
    - jaeger-client
    - jupyterlab >=2
    - pymapd
    - nodejs >=12
    - notebook
    - tornado
    - graphviz
    - altair
    - opentracing
    - ibis-framework
    - altair-transform
    - mypy_extensions
    - typing_extensions

test:
  imports:
    - ibis_vega_transform
  commands:
    - test -f ${PREFIX}/share/jupyter/lab/extensions/js/{{ name }}-{{ version }}.tgz

about:
  home: https://github.com/Quansight/ibis-vega-transform
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: Python evaluation of Vega transforms using Ibis expressions
  dev_url: https://github.com/Quansight/ibis-vega-transform

extra:
  recipe-maintainers:
    - scopatz
